[package]
name = "dwindle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
bincode = "2.0.0-rc.3"
log = "0.4.20"
once_cell = "1.19.0"
